### ISSUE TITLE
Handling input/output directory issue

### ISSUE THREAD

**Issue by gqjiang** [BD2KOnFHIR/fhirtordf#16]
fhirtordf -id synthea/output/fhir -o synthea/output/ttl --format ttl

caused a TypeError: 'NoneType' object is not iterable.

Loading FHIR metadata vocabulary...loaded from /Library/Python/3.7/site-packages/tests/data/fhir_metadata_vocabulary/fhir.ttl
Traceback (most recent call last):
  File "/usr/local/bin/fhirtordf", line 9, in <module>
    fhirtordf(sys.argv[1:])
  File "/Library/Python/3.7/site-packages/fhirtordf/fhirtordf.py", line 197, in fhirtordf
    nfiles, nsuccess = dlp.run(proc=proc_file, file_filter_2=file_filter)
  File "/Library/Python/3.7/site-packages/dirlistproc/DirectoryListProcessor.py", line 193, in run
    if self._check_filter(fn, dirpath, file_filter, file_filter_2):
  File "/Library/Python/3.7/site-packages/dirlistproc/DirectoryListProcessor.py", line 150, in _check_filter
    (not file_filter_2 or file_filter_2(fn, dirpath if dirpath is not None else '', self.opts)) and \
  File "/Library/Python/3.7/site-packages/fhirtordf/fhirtordf.py", line 123, in file_filter
    if indir and (indir.startswith("_") or "/_" in indir or any(dn in indir for dn in opts.skipdirs)):
TypeError: 'NoneType' object is not iterable

**Comment by hsolbrig** [comment]
Fixed
