### ISSUE TITLE
Error conversion resource fhir json to RDF

### ISSUE THREAD

**Issue by dmartino88** [BD2KOnFHIR/fhirtordf#23]
When I try to run the library in a docker container running on open shift I get the following error
`
Traceback (most recent call last):
  File "/usr/bin/fhirtordf", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/fhirtordf/fhirtordf.py", line 170, in main
    dlp.opts.fhir_metavoc = load_fhir_ontology(dlp.opts)
  File "/usr/lib/python3.6/site-packages/fhirtordf/fhirtordf.py", line 37, in load_fhir_ontology
    mv = FHIRMetaVoc(opts.metadatavoc)
  File "/usr/lib/python3.6/site-packages/fhirtordf/fhir/fhirmetavoc.py", line 160, in __init__
    self.g = picklejar().get(mv_file_loc, signature(mv_file_loc)) if cache_mv_file else None
  File "/usr/lib/python3.6/site-packages/fhirtordf/fhir/signature.py", line 61, in signature
    return url_signature(name) if is_url(name) else file_signature(name) if is_file(name) else None
  File "/usr/lib/python3.6/site-packages/fhirtordf/fhir/signature.py", line 49, in url_signature
    response = urllib.request.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Operation timed out>
`
When I run it on docker locally on my pc it works. Can someone tell me why I get this error and how can I fix it? I am running this command fhirtordf -i <path resource fhir json>.

**Comment by dmartino88** [comment]
Does this library need an internet connection to work?
